### ISSUE TITLE
求问大佬去年动态试商法的设计

### ISSUE THREAD

**Issue by NorbertZheng** [RickyTino/MangoMIPS32#1]
@RickyTino 柴可大佬您好，最近在研究您们去年参加龙芯杯的cpu设计。看到里面提到了除法器优化使用了动态试商法，我便上网查询相关资料，但没有太大的收获。不知您可不可以分享一些关于此方面的论文或者资料，如果可以得到您去年的除法器设计代码，将不胜感激。我的邮箱是fassial19991217@gmail.com，期待您的来信。谢谢！

**Comment by RickyTino** [comment]
你好~去年比赛除法器的代码是我队友写的，如果你需要的话我等他们睡醒了征求一下他们的同意。其实不妨告诉你，我们去年的实验结果表明动态试商法的除法器对于整体性能的提升非常的有限，大概性能分就提了0.01分这样子，所以不是很建议你在这部分上浪费太多时间啦。加油哦！

**Comment by NorbertZheng** [comment]
明白了 多谢大佬的建议！

**Comment by specialpointcentral** [comment]
除法大部分会被编译器优化成移位操作，所以提升很小。除法其实是一个非常有趣的算法，多少年来研究也不少，但都没有取得很多成果。现阶段最普遍的还是试商法，另外更优化的方法效率没有太多提升，但无论是算法复杂度还是其他方面都已经超过了一定的数量级。
对于我们使用的试商法，也仅仅是做了一些优化，比如特定情况采用移位等等操作。

reference:
https://janmr.com/blog/2009/08/implementing-multiple-precision-arithmetic-part-2/

**Comment by NorbertZheng** [comment]
多谢大佬的回复和建议！
